import AeroPuzzle from "../../assets/Project-img/AeroPuzzle.jpg";
import ZapShift from "../../assets/Project-img/ZapShift.png";
import BSPIBotForge from "../../assets/Project-img/BotForge.jpeg";
import HeroKidz from "../../assets/Project-img/HeroKidz.png";

export const projectsData = [
  {
    id: 1,
    title: "AeroPuzzle Game",
    description:
      "AI-powered browser-based hand gesture puzzle game that uses MediaPipe Hand Tracking for touchless interaction. Built with React 19, Vite, Tailwind CSS, DaisyUI, and MediaPipe Tasks Vision, featuring real-time pinch detection, live leaderboard, and secure authentication.",
    image: AeroPuzzle,
    topics: [
      "React 19",
      "Vite",
      "Tailwind CSS",
      "DaisyUI",
      "MediaPipe",
      "Hand Tracking",
      "AI",
      "Game",
      "Authentication",
      "Leaderboard",
      "Axios",
      "JavaScript",
      "Responsive UI",
    ],
    live: "https://aero-puzzle-front-end.vercel.app/",
    frontend: "https://github.com/mojahidmamu/AeroPuzzle_FrontEnd",
    backend: "https://github.com/mojahidmamu/AeroPuzzle_BackEnd",
  },
  {
    id: 2,
    title: "Zap Shift — Courier & Delivery Management Platform",
    description:
      "A full-stack courier and delivery management platform designed to streamline parcel delivery operations. Built with React, Node.js, Express.js, MongoDB, Firebase Authentication, and Stripe, featuring secure role-based access, parcel management, user dashboards, rider workflows, payment integration, and protected REST APIs.",
    image: ZapShift,
    topics: [
      "React.js",
      "Node.js",
      "Express.js",
      "JWT",
      "MongoDB",
      "Firebase",
      "REST API",
      "Firebase Authentication",
      "Parcel Management",
      "Stripe",
      "Role-Based Access",
      "Axios",
      "Rider Management",
      "Admin Dashboard",
      "Payment Integration",
      "Tailwind CSS",
      "DaisyUI",
      "JavaScript",
      "Responsive UI",
    ],
    live: "https://zap-shift-blush.vercel.app/",
    frontend: "https://github.com/mojahidmamu/Zap-Shift-Frontend",
    backend: "https://github.com/mojahidmamu/Zap-Shift-Backend",
  },
  {
    id: 3,
    title: "BSPI BotForge — Robotics Club Management & Member Portal",
    description:
      "A production-grade full-stack management platform built for BSPI Robotics Club to digitize membership operations, automate communication, and streamline club administration. Features a secure multi-admin system with email OTP authentication, automated membership approval workflow with real-time email notifications, dynamic member directory with department & blood group filtering (for emergency blood donation), event & notice management, bulk email newsletter system, transaction tracking, and comprehensive audit logs. Built with React, Node.js, Express.js, MongoDB, Firebase Authentication, Cloudinary, and Nodemailer, featuring role-based access control, protected REST APIs, image upload pipeline, and a fully responsive animated UI.",
    image: BSPIBotForge,
    topics: [
      "Vite",
      "MERN",
      "Mongoose",
      "JWT",
      "Firebase Authentication",
      "Admin Dashboard",
      "REST API",
      "Nodemailer",
      "Email OTP",
      "Cloudinary",
      "Role-Based Access Control",

      "Axios",
      "Framer Motion",
      "Bulk Email System",
      "Recharts",
      ,
      "Membership Management",
      "Event Management",
      "Blood Group Filter",
      "Audit Logs",
      "Responsive UI",
      "JavaScript",
      "Transaction Management",
      "Protected Routes",
      "Full-Stack Development",
    ],
    live: "",
    frontend: "https://github.com/mojahidmamu/BSPI-BotForge",
    backend: "https://github.com/mojahidmamu/BotForge-Server",
  },
  {
    id: 4,
    title: "Hero Kidz — Premium Kids E-Commerce Platform with Secure Payments",
    description:
      "Hero Kidz is a production-grade, single-vendor e-commerce platform built for selling premium children's educational products. It delivers a complete shopping journey — from browsing 20+ curated products to secure Stripe-powered checkout — with Google OAuth authentication, dynamic cart and wishlist management via Context API and localStorage, middleware-protected routes, and a personalized user profile with payment history. The platform also includes a Markdown-driven dynamic blog system, a Nodemailer-integrated contact form, and SEO-optimized metadata for every page. Built with Next.js 15 App Router, Server Components, and Framer Motion animations for a smooth, modern, and fully responsive experience.",
    image: HeroKidz,
    topics: [
      "Next.js 15",
      "App Router",
      "NextAuth.js",
      "Google OAuth",
      "Stripe",
      "Payment Gateway",
      "React.js",
      "Tailwind CSS",
      "DaisyUI",
      "Framer Motion",
      "React Icons",
      "Context API",
      "LocalStorage",
      "Middleware",
      "SSR",
      "Protected Routes",
      "Nodemailer",
      "Markdown Blog",
      "Gray-Matter",
      "Remark",
      "Server Components",
      "SEO Optimization",
      "Dynamic Routing",
      "Responsive UI",
      "Email Integration",
      "Cart Management",
      "JavaScript",
      "Wishlist System",
      "REST API",
      "User Profile Dashboard",
    ],
    live: "https://hero-kidz-ecru.vercel.app/",
    frontend: "https://github.com/mojahidmamu/HERO-Kids-NEXT",
  },
];
